<?php
/**
 * Created by PhpStorm.
 * Script Name: Base.php
 * Create: 2020/9/6 下午9:14
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\home\controller;

use app\common\service\Blog as BlogService;
use app\common\service\BlogColumn as ColumnService;
use think\facade\Db;

class Blog extends Base
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    function index(){
        $search_key = input('q', '');
        $column = input('keyword', '');
        $where = ['status' => 1];
        if($search_key){
            $where['title|desc|columns'] = ['like', "%$search_key%"];
        }
        if($column){
            $where['columns'] = ['like', "%$column%"];
        }

        $data_list = BlogService::model()->page(10, $where, ['top' => 'desc', 'recommend' => 'desc', 'id' => 'desc']);
        $page = $data_list->appends(['q' => $search_key, 'keyword' => $column])
            ->render();
        $assign = [
            'blog_list' => $data_list,
            'page' => $page,
            'hot_columns' => ColumnService::getHots(),
            'search_key' => $search_key,
            'column' => $column
        ];
        return $this->show($assign);
    }

    function detail(){
        $id = input('id', 0);
        $data = BlogService::model()->getOne($id);
        if(empty($data['status'])){
            $this->error("数据不存在！");
        }
        $columns = explode(',', $data['columns']);
        $or_arr = [];
        foreach ($columns as $column){
            $or_arr[] = 'columns like "%'.$column.'%"';
        }
        $sql = 'select id,title from ' . BlogService::model()->getTable() . ' where id <> '.$data['id'].' and status=1 and ('.implode(" or ", $or_arr).') order by view_num desc limit 0,5';

        $relate_list = Db::query($sql);
        //延迟生成incr view_num
        invoke('\\app\\common\\event\\TaskQueue')->push([
            'delay' => 3,
            'params' => [
                'do' => ['\\app\\common\\event\\Blog', 'incViewNum'],
                'blog' => $data
            ]
        ]);
        $assign = ['blog' => $data, 'relate_list' => $relate_list];
        return $this->show($assign);
    }
}