<?php
/**
 * Created by PhpStorm.
 * Script Name: AddonApiController.php
 * Create: 2023/8/4 16:57
 * Description: 应用中接口模块的基础控制器
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\addon;

use ky\ErrorCode;

class AddonApiController extends AddonController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * 操作成功跳转的快捷方法
     * @param string $msg
     * @param string $data
     * @param int $code
     * @param array $header
     * @return \think\response\Json
     */
    protected function jSuccess($msg = '操作失败!', $data = '', int $code = ErrorCode::SuccessCode, array $header = [])
    {
        $result = [
            'code'  => $code,
            'msg'   => $msg,
            'data'  => $data
        ];
        return json($result, 200, $header);
    }

    /**
     * @param string $msg
     * @param int $code
     * @param string $data
     * @param array $header
     * Author: fudaoji<fdj@kuryun.cn>
     * @return \think\response\Json
     */
    protected function jError($msg = '操作失败!', int $code = ErrorCode::BadParam, $data = '', array $header = [])
    {
        $result = [
            'code' => $code,
            'msg'  => $msg,
            'data' => $data
        ];
        return json($result, 200, $header);
    }
}