<?php
/**
 * Created by PhpStorm.
 * Script Name: Bbase.php
 * Create: 2021/12/21 12:37
 * Description: 客户功能基础类
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\admin\controller;
use app\constants\Media;

class Bbase extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 设置一条或者多条数据的状态
     * @Author  fudaoji<fdj@kuryun.cn>
     */
    public function setStatus() {
        $ids = input('ids/a');
        $status = input('status');

        if (empty($ids)) {
            $this->error('请选择要操作的数据');
        }

        $ids = (array) $ids;
        foreach ($ids as $id){
            $this->model->delOne(['id' => $id, 'admin_id' => $this->adminInfo['id']]);
        }
        $this->success('删除成功');
    }

    /**
     * 保存数据
     * @param string $jump_to
     * @param array $data
     * @return mixed
     */
    public function savePost($jump_to = '', $data=[]){
        $post_data = $data ? $data : input('post.');
        $post_data['admin_id'] = $this->adminInfo['id'];
        if(empty($post_data[$this->pk])){
            $res = $this->model->addOne($post_data);
        }else {
            $res = $this->model->updateOne($post_data);
        }

        if($res){
            $this->success('数据保存成功', $jump_to);
        }else{
            $this->error('数据保存出错');
        }
    }

    public function mediaTabs(){
        return [
            Media::TEXT => ['title' => '文本', 'href' => url('mediatext/index')],
            Media::IMAGE => ['title' => '图片', 'href' => url('mediaimage/index')],
            Media::FILE => ['title' => '文件', 'href' => url('mediafile/index')],
            Media::VIDEO => ['title' => '视频', 'href' => url('mediavideo/index')]
        ];
    }
}