<?php
/**
 * Created by PhpStorm.
 * Script Name: Botbase.php
 * Create: 2021/12/21 12:37
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\admin\controller;


class Botbase extends Bbase
{
    protected $botList = [];
    protected $bot;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->bot = model('bot')->getOneByMap(['admin_id' => $this->adminInfo['id'], 'is_current' => 1]);
        if(empty($this->bot)){
            $this->error('请选择机器人操作', url('bot/index'));
        }
        $this->botList = model('bot')->getField(['id','title'], ['status' => 1]);
        $this->assign['bot_info'] = $this->bot;
        $this->assign['bot_list'] = $this->botList;
    }
}