<?php

/**
 * Created by PhpStorm.
 * Script Name: Setting.php
 * Create: 2020/5/24 上午10:25
 * Description: 站点配置
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\admin\controller;
use app\common\model\Reply as ReplyM;
use app\constants\Reply as ReplyConst;

class Reply extends Botbase
{
    /**
     * @var ReplyM
     */
    protected $model;
    private $tabList;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new ReplyM();
        $events = ReplyConst::events();
        foreach ($events as $k => $v){
            $this->tabList[$k] = [
                'title' => $events[$k],
                'href' => url('index', ['event' => $k])
            ];
        }
    }

    /**
     *
     * @return mixed
     * @throws \think\Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * Author: fudaoji<fdj@kuryun.cn>
     */
    public function copy()
    {
        if(request()->isPost()){
            $post_data = input('post.');
            $exists = $this->model->getField(['media_id'], ['bot_id' => $this->bot['id']]);
            $list = $this->model->getAll([
                'where' => ['bot_id' => $post_data['bot_id'], 'status' => 1, 'media_id' => ['notin', $exists]],
                'refresh' => true
            ]);
            foreach ($list as $v){
                unset($v['id']);
                $v['bot_id'] = $this->bot['id'];
                $this->model->addOne($v);
            }
            $this->success('操作成功');
        }
        $bot_list = $this->getBots(['id' => ['neq', $this->bot['id']]]);
        // 使用FormBuilder快速建立表单页面
        $builder = new FormBuilder();
        $builder->setMetaTitle('复制内容')
            ->setPostUrl(url('copy'))
            ->addFormItem('bot_id', 'chosen', '机器人', '请选择', $bot_list, 'required');

        return $builder->show();
    }

    /**
     * 设置
     * @return mixed
     * @throws \think\Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @throws \think\exception\PDOException
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function index(){
        $current_name = input('event', ReplyConst::BEADDED);
        $reply = $this->model->getOneByMap(['event' => $current_name, 'bot_id' => $this->bot['id']], true, true);
        if(request()->isPost()){
            $post_data = input('post.');
            if(empty($reply)){
                $res = $this->model->addOne($post_data);
            }else{
                $res = $this->model->updateOne($post_data);
            }
            if($res){
                $this->success('保存成功');
            }else{
                $this->error('保存失败，请刷新重试', '', ['token' => request()->token()]);
            }
        }

        $builder = new FormBuilder();
        $material = [];
        if(empty($reply)){
            $reply = [
                'admin_id' => $this->adminInfo['id'],
                'bot_id' => $this->bot['id'],
                'media_id' => 0,
                'media_type' => '',
                'event' => $current_name
            ];
        }else{
            $material = model('media_' . $reply['media_type'])->getOneByMap([
                'admin_id' => $reply['admin_id'],
                'id' => $reply['media_id']
            ], true, true);
            if(!empty($reply['wxids'])){
                $reply['wxids'] = explode(',', $reply['wxids']);
            }
            $builder->addFormItem('id', 'hidden', 'id', 'id');
        }
        $builder->addTopButton('addnew', ['title' => '从其他机器人复制', 'href' => url('copy'), 'class' => 'layui-btn layui-btn-sm'])
            ->addFormItem('admin_id', 'hidden', 'adminid', 'adminid')
            ->addFormItem('bot_id', 'hidden', 'botid', 'botid')
            ->addFormItem('event', 'hidden', 'event', 'event')
            ->addFormItem('media', 'choose_media', '回复内容', '回复内容', ['types' => \app\constants\Media::types(), 'id' => $reply['media_id'], 'type' => $reply['media_type']], 'required')
            ->setFormData($reply);
        switch ($current_name){
            case ReplyConst::FRIEND_IN:
                $groups = $this->getGroups();
                $builder->addFormItem('wxids', 'chosen_multi', '指定群', '指定群', $groups, 'required');
                break;
        }
        return $builder->addFormItem('status', 'radio', '状态', '状态', [1 => '启用', 0 => '禁用'], 'required')
            ->show(['tab_nav' => ['tab_list' => $this->tabList, 'current_tab' => $current_name], 'material' => $material]);
    }
}