<?php
/**
 * Created by PhpStorm.
 * Script Name: Test.php
 * Create: 12/20/21 11:49 PM
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\admin\controller;

use app\admin\model\Goods;
use ky\Bot\Wx;
use ky\Bot\Wxwork;

class Test extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function testPregMatch(){
        $content = "@每日里客服[emoji=\u00A0][弱]";
        if(($pos1 = strpos($content, "@") !== false) && ($pos2 = strpos($content, "[")) !== false){
            $matches = trim(substr($content, $pos1, $pos2-1));
        }
        //$res = preg_match("/^@(.*)(?:\[emoji=\\\\u2005\]|\[emoji=\\u00A0\]).*\[弱\]/", $content, $matches);
        dump($matches);
    }

    public function vbot(){
        $bot = new Wxwork(['app_key' => 'quNhWFeMrTcsjPnUIUtcpZHMHcAsEDRq', 'base_uri' => '124.222.4.168:8090']);
        $res = $bot->getFriends(['robot_wxid' => '1688856404324777']);
        dump($res);exit;
    }

}