<?php
/**
 * Created by PhpStorm.
 * Script Name: EventFrieneVerify.php
 * Create: 3/19/22 9:19 PM
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\bot\handler\cat;


use app\bot\controller\Api;
use ky\Logger;

class EventFriendVerify extends Api
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    public function handle(){
        Logger::error($this->content);
    }
}