<?php


namespace app\bot\controller;
use app\common\model\kefu\ChatLog;
use app\common\model\kefu\Kefu as KefuModel;
class Kefu extends Addon
{
    private $switch;
    private $toWxid = '';
    public function init($options = [])
    {
        parent::init($options); // TODO: Change the autogenerated stub
        $this->switch = true;
        return $this;
    }


    /**
     * 私聊处理器
     * Author: fudaoji<fdj@kuryun.cn>
     */
    public function privateChatHandle(){
        if(empty($this->switch)){
            return false;
        }
        $this->toWxid = $this->fromWxid;
        //保存私聊消息
        $model_chat_log = new ChatLog();
        $model_chat_log->saveChat($this->content,$this->bot);
    }

    /**
     * 
     * 好友请求处理器
     */
    public function frieneVerifyHandle(){
        //自动通过好友验证
        $model_kefu = new KefuModel();
        $model_kefu->autoPass($this->content,$this->bot,$this->botClient);
    }
    
}
