<?php
/**
 * Created by PhpStorm.
 * Script Name: Adminseat.php
 * Create: 2023/2/18 9:56
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\admin\controller;


class Adminseat extends Bbase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //下单页面
    public function order(){

    }

    //支付页面
    public function pay(){

    }
}