<?php
/**
 * Created by PhpStorm.
 * Script Name: Botbase.php
 * Create: 2021/12/21 12:37
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\admin\controller;


use app\constants\Bot;

class Botbase extends Bbase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //$this->bot = $this->getCurrentBot();
        if(empty($this->bot)){
            $this->error('请选择机器人操作', url('bot/index'));
        }
        /*$this->botList = $this->getBots();
        $this->assign['bot_info'] = $this->bot;
        $this->assign['bot_list'] = $this->botList;*/
    }

    public function getGroups($where = []){
        $where = array_merge(['uin' => $this->bot['uin'], 'type' => Bot::GROUP], $where);
        return model('admin/botMember')->getField('wxid,nickname', $where, true);
    }

    public function getMembers($where = []){
        $where = array_merge(['uin' => $this->bot['uin']], $where);
        return model('admin/botMember')->getField('wxid,nickname', $where, true);
    }
}