<?php
/**
 * Created by PhpStorm.
 * Script Name: Test.php
 * Create: 12/20/21 11:49 PM
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\admin\controller;

use app\admin\model\Goods;
use ky\WxBot\Wx;
use ky\WxBot\Wxwork;
use ky\Jtt;

class Test extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function testJtt(){
        $keyword = "草莓干";
        $page_size = 3;
        $unionid = "2025003964";
        $positionid = "3004264525";
        $jtt = new Jtt(['appid' => config('system.site.jtt_appid'), 'appkey' => config('system.site.jtt_appkey')]);
        $res = $jtt->jdGoodsQuery([
            'v' => 'v3', 'keyword' => $keyword, 'sortName' => 'inOrderCount30Days', 'sort' => 'desc', 'isCoupon' => 1,
            'pageSize' => $page_size
        ]);

        $template = "[商品标题]
京东价：[商品原价]元
抢购价：[优惠价]元
领券+下单：[抢购链接]";
        $content = "暂未找到相关内容，您可以点击以下链接自助查询哦：
https://union-click.jd.com/jdc?e=618%7Cpc%7C&p=JF8BAOkJK1olXDYDZBoCUBVIMzZNXhpXVhgcDVpCVFRMVnBaRQcLDlZRAAMoUAMJaDtMWUVzBnF0ACcPYABWAxJTTjt9HnUGFigtWC9rXz8WQwRACU8dDRsBVUVWUzlcYw4ZBFhHZBkLYAtWBjp-eCBjIhwECQ5DEgBzZR8EF2sQXQcDU1ddC04eM2wJGF8UXAQKU1ttOEsUMyRmGmsXXAcHV1lYDEgTM28PHlIcVAABUF5UDk4nBG8BKwBAMwNEHz0jCCNzRBNAeF5QHzYyZF1tD0seF2l6WgkBW3QyZF9tC3tIRzJVK1kUXAILZA
";
        if(!empty($res['totalCount'])){
            $content = "为您查询到以下".count($res['goods'])."个商品：\r\n\r\n";
            foreach ($res['goods'] as $k => $goods){
                $link = $goods['goods_link'];
                if(!empty($goods['couponInfo']['couponList'][0]['discount_link'])){
                    $coupon_link = $goods['couponInfo']['couponList'][0]['discount_link'];
                    $link = $coupon_link . "\r\n" . $goods['goods_link'];
                }

                if($k + 1 >= count($res['goods'])){
                    $link .= "\r\n-------------------------------------------\r\n\r\n如果您对查询结果不满意，可以自主查询：\r\nhttps://union-click.jd.com/jdc?e=618%7Cpc%7C&p=JF8BAOkJK1olXDYDZBoCUBVIMzZNXhpXVhgcDVpCVFRMVnBaRQcLDlZRAAMoUAMJaDtMWUVzBnF0ACcPYABWAxJTTjt9HnUGFigtWC9rXz8WQwRACU8dDRsBVUVWUzlcYw4ZBFhHZBkLYAtWBjp-eCBjIhwECQ5DEgBzZR8EF2sQXQcDU1ddC04eM2wJGF8UXAQKU1ttOEsUMyRmGmsXXAcHV1lYDEgTM28PHlIcVAABUF5UDk4nBG8BKwBAMwNEHz0jCCNzRBNAeF5QHzYyZF1tD0seF2l6WgkBW3QyZF9tC3tIRzJVK1kUXAILZA";
                }else{
                    $link .= "\r\n-------------------------------------------\r\n";
                }

                $count = 0;
                do{
                    $reply_content = $jtt->universal([
                        'unionid' => $unionid,
                        'positionid' => $positionid,
                        'content' => $link
                    ]);
                    $count++;
                    if($count >= 2) break;
                }while($reply_content === false);

                if($reply_content && !empty($reply_content['chain_content'])){
                    $link = ltrim($reply_content['chain_content'], "\r\n");
                }

                $temp_content = str_replace(
                    ['[商品标题]', '[商品原价]', '[优惠价]', '[抢购链接]'],
                    [$goods['skuName'], $goods['priceInfo']['goods_price'], $goods['priceInfo']['lowestCouponPrice'], $link],
                    $template
                );

                $content .= $temp_content;
            }
        }else{
            $reply_content = $jtt->universal([
                'unionid' => $unionid,
                'positionid' => $positionid,
                'content' => $content,
                'v' => 'v2'
            ]);
            $content = $reply_content['chain_content'];
        }

        dump($content);exit;
    }

    public function testPregMatch()
    {
        $content = "@每日里客服[emoji=\u00A0][弱]";
        if (($pos1 = strpos($content, "@") !== false) && ($pos2 = strpos($content, "[")) !== false) {
            $matches = trim(substr($content, $pos1, $pos2 - 1));
        }
        //$res = preg_match("/^@(.*)(?:\[emoji=\\\\u2005\]|\[emoji=\\u00A0\]).*\[弱\]/", $content, $matches);
        dump($matches);
    }

    public function vbot(){
        $bot = new Wxwork(['app_key' => 'quNhWFeMrTcsjPnUIUtcpZHMHcAsEDRq', 'base_uri' => '124.222.4.168:8090']);
        $res = $bot->getFriends(['robot_wxid' => '1688856404324777']);
        dump($res);exit;
    }

}