<?php

namespace app\admin\controller;

use app\common\model\zdjr\Config;
use app\constants\Bot;

class Zdjrconfig extends Botbase
{
    /**
     * @var Config
     */
    protected $model;
    /**
     * @var array
     */
    private $tabList;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new Config();
        $this->tabList = [

        ];
    }

    /**
     * 设置
     * @return mixed
     * @throws \think\Exception
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function index(){
        $settings = $this->model->getConf(['admin_id' => $this->adminInfo['id']], '', true);
        $builder = new FormBuilder();
        $builder->setPostUrl(url('savePost'))
            //->addFormItem('basic_legend', 'legend', '基础配置','基础配置' )
            ->addFormItem('apply_perday', 'number', '每天加友上限', '每个机器人每天加好友上限，为安全起见，建议不超过10', [], 'required min=1 max=20')
            ->setFormData($settings);
        return $builder->show();
    }

    public function savePost($jump_to = '/undefined', $data = [])
    {
        $jump_to = url('index');
        $post_data = input('post.');
        unset($post_data['__token__']);
        foreach ($post_data as $k => $v){
            if($config = $this->model->getOneByMap(['bot_id' => $this->bot['id'], 'key' => $k],  true, true)){
                $this->model->updateOne(['id' => $config['id'], 'value' => $v]);
            }else{
                $this->model->addOne([
                    'admin_id' => $this->adminInfo['id'],
                    //'bot_id' => $this->bot['id'],
                    'key' => $k,
                    'value'=> $v
                ]);
            }
            $this->model->getConf(['admin_id' => $this->adminInfo['id']], $k, true);
        }
        $this->success('数据保存成功', $jump_to);
    }
}