<?php
/**
 * Created by PhpStorm.
 * Script Name: EventPrivateChat.php
 * Create: 3/19/22 11:14 PM
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\bot\handler\vlw;


use app\bot\controller\Api;
use ky\Helper;
use ky\Logger;

class EventPrivateChat extends Api
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        return $this;
    }

    /**
     * 私聊消息接收器
     */
    public function handle(){
        $fdj = "wxid_xokb2ezu1p6t21";
        $qy_exter_yxg = '1688856404324777';
        $qy_group = 'R:10951134140940878';
        $yyp = 'weiwei562608';
        $jane = "wxid_a98qqf9m4bny22";

        //Logger::error("privateChat".json_encode($this->content, JSON_UNESCAPED_UNICODE));
        if($this->fromWxid == $qy_exter_yxg){
            $res = $this->botClient->sendImgToFriends([
                'robot_wxid' => $this->botWxid,
                'to_wxid' => $qy_exter_yxg,
                'path' => "https://www.liangcang.cc/static/img/qrcode.c2f2668b.png"
            ]);
            //Logger::error(json_encode($res, JSON_UNESCAPED_UNICODE));
        }
    }
}