<?php
/**
 * Created by PhpStorm.
 * Script Name: Base.php
 * Create: 2022/7/7 11:23
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\install\controller;


use think\Controller;

class Base extends Controller
{
    protected $assign = [];
    protected $module;
    protected $controller;
    protected $action;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (request()->action() != 'complete' && is_file(app()->getRootPath() . '/install.lock')) {
            $this->redirect('admin/index/index');
        }

        $this->module = strtolower(request()->module());
        $this->controller = strtolower(request()->controller());
        $this->action = strtolower(request()->action());
    }

    /**
     * 统一视图
     * @param string $view
     * @param array $assign
     * @return mixed
     * @Author  fudaoji<fdj@kuryun.cn>
     */
    public function show($assign = [], $view = ''){
        $assign['module'] = $this->module;
        $assign['controller'] = $this->controller;
        $assign['action'] = $this->action;
        $assign['company'] = '厦门酷云网络科技有限公司';
        $assign['official_web'] = 'https://kyphp.kuryun.com/home/guide/bot.html';

        $this->assign = array_merge($this->assign, $assign);

        if (!$view) {
            $view = $assign['action'];
        }
        return $this->fetch($view, $this->assign);
    }
}