<?php
/**
 * Created by PhpStorm.
 * Script Name: Hanzi.php
 * Create: 5/23/22 9:31 AM
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\wap\controller;


use app\common\controller\BaseCtl;

class Hanzi extends BaseCtl
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $text = input("text", "汉字");
        $meta_title = "每日里汉语学习工具";
        $assign = ['text' => $text, 'meta_title' => $meta_title];
        return $this->show($assign);
    }
}